package m0rjc.ax25.generator.picAsmBuilder;

import java.io.IOException;
import java.io.Writer;
import java.util.logging.Level;
import java.util.logging.Logger;

/** Methods to write assembler */
class PicAssemblyWriter
{
	private boolean m_fileStarted;
	private final Writer m_out;
	private boolean m_error;
	protected Logger m_log = Logger.getLogger(getClass().getName());

	/** Label to output on the next command */
	private String m_currentLabel;

	private PicAssemblyWriter(Writer out)
	{
		m_out = out;
	}

	/**
	 * Output a big comment line of dashes
	 */
	public void startBlockComment()
	{
		write(";------------------------------------------------------------------------------\n");
	}
	
	/**
	 * Output a line of text as a full line comment
	 */
	public void writeBlockCommentLine(String line)
	{
		write("; ");
		write(line);
		write("\n");
	}
	
	/**
	 * Output a big comment line of dashes
	 */
	public void endBlockComment()
	{
		write(";------------------------------------------------------------------------------\n");		
	}
	
	/**
	 * Output inline comment for assembler
	 */
	public void writeComment(String string)
	{
		write("              ; ");
		write(string);
		write("\n");
	}
	
	/** Output an assembler label. Will be output on next instruction. */
	public void writeLabel(String label)
	{
		if(m_currentLabel != null)
		{
			write(m_currentLabel + ":\n");
		}
		m_currentLabel = label;
	}

	
	/** Write a line of assembler */
	public void opCode(String opCode, String... args)
	{
		if(m_currentLabel != null)
		{
			write(String.format("%-12s: ", m_currentLabel));
		}
		else
		{
			write("              ");
		}
		m_currentLabel = null;
		
		write(String.format("%-8s ", opCode));
		
		boolean comma = false;
		for(String arg : args)
		{
			if(comma) write(", ");
			write(arg);
			comma = true;
		}
		write("\n");
	}

	/**
	 * Output a section marker
	 * @param linkerName
	 * @param sectionType
	 */
	public void writeSection(String linkerName, String sectionType)
	{
		write(String.format("%-12s  %s\n", linkerName, sectionType));
	}
	
	/**
	 * Write the END marker
	 */
	public void writeEndMarker()
	{
		writeSection("","END");
	}
	
	/** Encode <code>name res size</code> */
	public void ramResourceAllocation(String name, int size)
	{
		write(String.format(" %12s res .%d\n", name, size));
	}

	/** Write a blank line to the output file */
	public void blankLine()
	{
		write("\n");
	}


	
	/** Write to the output, handling error if needed */
	protected void write(String line)
	{
		if(!m_fileStarted)
		{
			m_fileStarted = true; // Prevent infinite recursion
			startFile();
		}
		
		if(!m_error)
		{
			try
			{
				m_out.write(line);
			}
			catch (IOException e)
			{
				m_error = true;
				m_log.log(Level.SEVERE, "Unable to write to output file", e);
				try
				{
					m_out.close();
				}
				catch (Exception e2) {}
			}
		}
	}

	/** Output the start of file header */
	private void startFile()
	{
		startBlockComment();
		writeBlockCommentLine("This file was auto-generated by PICStateGenerator. Do not edit.");
		endBlockComment();
	}
}
