;------------------------------------------------------------------------------
; This file was auto-generated by PICStateGenerator. Do not edit.
; Generated: Tue Nov 15 22:27:57 GMT 2011
;------------------------------------------------------------------------------
              list     p=18F14K50
#include "p18f14k50.inc"

              GLOBAL   gpsInit
              GLOBAL   gpsStep
              GLOBAL   gpsLatitudeDegMin
              GLOBAL   gpsFlags
              GLOBAL   gpsLongitudeHundredths
              GLOBAL   gpsTime
              GLOBAL   testSendVar
              GLOBAL   gpsLongitudeDegMin
              GLOBAL   gpsQuality
              GLOBAL   testSendIndex
              GLOBAL   gpsLatitudeHundredths
              GLOBAL   gpsInput

gpsAcs        UDATA_ACS
_statePtr              res .2
_subReturn             res .2
gpsFlags               res .2
gps_storeCount         res .1
gpsInput               res .1

              ; Please set up the linker to locate this block as required.
gpsBank1      UDATA
gpsLatitudeDegMin      res .4
gpsLongitudeHundredths   res .2
gpsTime                res .6
testSendVar            res .1
gpsLongitudeDegMin     res .5
gpsQuality             res .1
testSendIndex          res .1
gpsLatitudeHundredths   res .2

gpsCode       CODE

;------------------------------------------------------------------------------
; State model initialisation.
;------------------------------------------------------------------------------
gpsInit:      MOVLW    HIGH(step_root)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(step_root)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; State model entry point.
; This method executes the code for the current state.
;------------------------------------------------------------------------------
gpsStep:      CLRF     PCLATU, A
              MOVFF    (_statePtr + .1), PCLATH
              MOVF     _statePtr, W, A
              MOVWF    PCL, A

;------------------------------------------------------------------------------
; Node root entry code.
;------------------------------------------------------------------------------
              ;  Command PORTC:0 := false
enter_root:   BCF      PORTC, 0, A
              ;  Transition GOTO root
              MOVLW    HIGH(step_root)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(step_root)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; Node root step code.
;------------------------------------------------------------------------------
                ; -- Start of transition --
                ;  Precondition gpsInput == '$'
step_root:      MOVLW    .36
                CPFSEQ   gpsInput, A
                GOTO     lbl_0
                ;  Transition GOTO (Shared) dollar
                GOTO     enter_dollar
                ; -- Start of transition --
                ;  Precondition gpsInput == '!'
lbl_0:          MOVLW    .33
                CPFSEQ   gpsInput, A
                GOTO     lbl_1
                ;  Transition GOTO (Shared) gps_State_0000
                GOTO     enter_gps_State_0000
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_1:          GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0000 entry code.
;------------------------------------------------------------------------------
lbl_2:
              ;  Transition GOTO gps_State_0000
enter_gps_State_0000: MOVLW    HIGH(step_gps_State_0000)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(step_gps_State_0000)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; Node gps_State_0000 step code.
;------------------------------------------------------------------------------
                ; -- Start of transition --
                ;  Precondition gpsInput == '!'
step_gps_State_0000: MOVLW    .33
                CPFSEQ   gpsInput, A
                GOTO     lbl_3
                ;  Precondition Flag gpsFlags:3 == false
                BTFSC    gpsFlags, 3, A
                GOTO     lbl_3
                ;  Command PORTC:1 := true
                BSF      PORTC, 1, A
                ;  Transition GOTO gps_State_0001
                MOVLW    HIGH(step_gps_State_0001)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0001)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_3:          GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0001 step code.
;------------------------------------------------------------------------------
lbl_4:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'T'
step_gps_State_0001: MOVLW    .84
                CPFSEQ   gpsInput, A
                GOTO     lbl_5
                ;  Transition GOTO gps_State_0002
                MOVLW    HIGH(step_gps_State_0002)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0002)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Precondition gpsInput == 'S'
lbl_5:          MOVLW    .83
                CPFSEQ   gpsInput, A
                GOTO     lbl_6
                ;  Transition GOTO gps_State_0017
                MOVLW    HIGH(step_gps_State_0017)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0017)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_6:          GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0002 step code.
;------------------------------------------------------------------------------
lbl_7:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'E'
step_gps_State_0002: MOVLW    .69
                CPFSEQ   gpsInput, A
                GOTO     lbl_8
                ;  Transition GOTO gps_State_0003
                MOVLW    HIGH(step_gps_State_0003)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0003)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_8:          GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0003 step code.
;------------------------------------------------------------------------------
lbl_9:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'S'
step_gps_State_0003: MOVLW    .83
                CPFSEQ   gpsInput, A
                GOTO     lbl_10
                ;  Transition GOTO gps_State_0004
                MOVLW    HIGH(step_gps_State_0004)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0004)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_10:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0004 step code.
;------------------------------------------------------------------------------
lbl_11:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'T'
step_gps_State_0004: MOVLW    .84
                CPFSEQ   gpsInput, A
                GOTO     lbl_12
                ;  Transition GOTO gps_State_0005
                MOVLW    HIGH(step_gps_State_0005)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0005)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_12:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0005 step code.
;------------------------------------------------------------------------------
lbl_13:
                ; -- Start of transition --
                ;  Precondition gpsInput == '-'
step_gps_State_0005: MOVLW    .45
                CPFSEQ   gpsInput, A
                GOTO     lbl_14
                ;  Transition GOTO gps_State_0006
                MOVLW    HIGH(step_gps_State_0006)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0006)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_14:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0006 step code.
;------------------------------------------------------------------------------
lbl_15:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'S'
step_gps_State_0006: MOVLW    .83
                CPFSEQ   gpsInput, A
                GOTO     lbl_16
                ;  Transition GOTO gps_State_0007
                MOVLW    HIGH(step_gps_State_0007)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0007)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_16:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0007 step code.
;------------------------------------------------------------------------------
lbl_17:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'E'
step_gps_State_0007: MOVLW    .69
                CPFSEQ   gpsInput, A
                GOTO     lbl_18
                ;  Transition GOTO gps_State_0008
                MOVLW    HIGH(step_gps_State_0008)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0008)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_18:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0008 step code.
;------------------------------------------------------------------------------
lbl_19:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'N'
step_gps_State_0008: MOVLW    .78
                CPFSEQ   gpsInput, A
                GOTO     lbl_20
                ;  Transition GOTO gps_State_0009
                MOVLW    HIGH(step_gps_State_0009)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0009)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_20:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0009 step code.
;------------------------------------------------------------------------------
lbl_21:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'D'
step_gps_State_0009: MOVLW    .68
                CPFSEQ   gpsInput, A
                GOTO     lbl_22
                ;  Transition GOTO gps_State_0010
                MOVLW    HIGH(step_gps_State_0010)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0010)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_22:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0010 step code.
;------------------------------------------------------------------------------
lbl_23:
                ; -- Start of transition --
                ;  Precondition gpsInput == ':'
step_gps_State_0010: MOVLW    .58
                CPFSEQ   gpsInput, A
                GOTO     lbl_24
                ;  Command gps_storeCount := 0
                CLRF     gps_storeCount, A
                ;  Command testSendVar := 0
                BANKSEL  testSendVar
                CLRF     testSendVar
                ;  Transition GOTO gps_State_0011
                MOVLW    HIGH(step_gps_State_0011)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0011)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_24:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0011 step code.
;------------------------------------------------------------------------------
lbl_25:
                ; -- Start of transition --
                ;  Precondition gpsInput >= '0'
step_gps_State_0011: MOVLW    .47
                CPFSGT   gpsInput, A
                GOTO     lbl_26
                ;  Precondition gpsInput <= '9'
                MOVLW    .58
                CPFSLT   gpsInput, A
                GOTO     lbl_26
                ;  Command testSendVar[gps_storeCount] := gpsInput
                LFSR     FSR0, testSendVar
                MOVF     gps_storeCount, W, A
                MOVFF    gpsInput, PLUSW0
                ;  Command gps_storeCount++
                INCF     gps_storeCount, F, A
                ;  Transition GOTO gps_State_0012
                MOVLW    HIGH(step_gps_State_0012)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0012)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_26:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0012 step code.
;------------------------------------------------------------------------------
lbl_27:
                ; -- Start of transition --
                ;  Precondition gpsInput == ':'
step_gps_State_0012: MOVLW    .58
                CPFSEQ   gpsInput, A
                GOTO     lbl_28
                ;  Command gps_storeCount := 0
                CLRF     gps_storeCount, A
                ;  Command testSendIndex := 0
                BANKSEL  testSendIndex
                CLRF     testSendIndex
                ;  Transition GOTO gps_State_0013
                MOVLW    HIGH(step_gps_State_0013)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0013)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_28:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0013 step code.
;------------------------------------------------------------------------------
lbl_29:
                ; -- Start of transition --
                ;  Precondition gpsInput >= '0'
step_gps_State_0013: MOVLW    .47
                CPFSGT   gpsInput, A
                GOTO     lbl_30
                ;  Precondition gpsInput <= '9'
                MOVLW    .58
                CPFSLT   gpsInput, A
                GOTO     lbl_30
                ;  Command testSendIndex[gps_storeCount] := gpsInput
                LFSR     FSR0, testSendIndex
                MOVF     gps_storeCount, W, A
                MOVFF    gpsInput, PLUSW0
                ;  Command gps_storeCount++
                INCF     gps_storeCount, F, A
                ;  Transition GOTO gps_State_0014
                MOVLW    HIGH(step_gps_State_0014)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0014)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_30:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0014 step code.
;------------------------------------------------------------------------------
lbl_31:
                ; -- Start of transition --
                ;  Precondition gpsInput == '!'
step_gps_State_0014: MOVLW    .33
                CPFSEQ   gpsInput, A
                GOTO     lbl_32
                ;  Transition GOTO gps_State_0015
                MOVLW    HIGH(step_gps_State_0015)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0015)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_32:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0015 step code.
;------------------------------------------------------------------------------
lbl_33:
                ; -- Start of transition --
                ;  Precondition gpsInput == '!'
step_gps_State_0015: MOVLW    .33
                CPFSEQ   gpsInput, A
                GOTO     lbl_34
                ;  Command gpsFlags:3 := true
                BSF      gpsFlags, 3, A
                ;  Command PORTC:1 := false
                BCF      PORTC, 1, A
                ;  Transition GOTO (Shared) root
                GOTO     enter_root
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_34:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0017 step code.
;------------------------------------------------------------------------------
lbl_35:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'E'
step_gps_State_0017: MOVLW    .69
                CPFSEQ   gpsInput, A
                GOTO     lbl_36
                ;  Transition GOTO gps_State_0018
                MOVLW    HIGH(step_gps_State_0018)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0018)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_36:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0018 step code.
;------------------------------------------------------------------------------
lbl_37:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'T'
step_gps_State_0018: MOVLW    .84
                CPFSEQ   gpsInput, A
                GOTO     lbl_38
                ;  Transition GOTO gps_State_0019
                MOVLW    HIGH(step_gps_State_0019)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0019)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_38:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0019 step code.
;------------------------------------------------------------------------------
lbl_39:
                ; -- Start of transition --
                ;  Precondition gpsInput == '-'
step_gps_State_0019: MOVLW    .45
                CPFSEQ   gpsInput, A
                GOTO     lbl_40
                ;  Transition GOTO gps_State_0020
                MOVLW    HIGH(step_gps_State_0020)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0020)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_40:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0020 step code.
;------------------------------------------------------------------------------
lbl_41:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'T'
step_gps_State_0020: MOVLW    .84
                CPFSEQ   gpsInput, A
                GOTO     lbl_42
                ;  Transition GOTO gps_State_0021
                MOVLW    HIGH(step_gps_State_0021)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0021)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_42:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0021 step code.
;------------------------------------------------------------------------------
lbl_43:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'E'
step_gps_State_0021: MOVLW    .69
                CPFSEQ   gpsInput, A
                GOTO     lbl_44
                ;  Transition GOTO gps_State_0022
                MOVLW    HIGH(step_gps_State_0022)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0022)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_44:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0022 step code.
;------------------------------------------------------------------------------
lbl_45:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'S'
step_gps_State_0022: MOVLW    .83
                CPFSEQ   gpsInput, A
                GOTO     lbl_46
                ;  Transition GOTO gps_State_0023
                MOVLW    HIGH(step_gps_State_0023)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0023)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_46:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0023 step code.
;------------------------------------------------------------------------------
lbl_47:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'T'
step_gps_State_0023: MOVLW    .84
                CPFSEQ   gpsInput, A
                GOTO     lbl_48
                ;  Transition GOTO gps_State_0024
                MOVLW    HIGH(step_gps_State_0024)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0024)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_48:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0024 step code.
;------------------------------------------------------------------------------
lbl_49:
                ; -- Start of transition --
                ;  Precondition gpsInput == '-'
step_gps_State_0024: MOVLW    .45
                CPFSEQ   gpsInput, A
                GOTO     lbl_50
                ;  Transition GOTO gps_State_0025
                MOVLW    HIGH(step_gps_State_0025)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0025)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_50:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0025 step code.
;------------------------------------------------------------------------------
lbl_51:
                ; -- Start of transition --
                ;  Precondition gpsInput == '9'
step_gps_State_0025: MOVLW    .57
                CPFSEQ   gpsInput, A
                GOTO     lbl_52
                ;  Transition GOTO gps_State_0026
                MOVLW    HIGH(step_gps_State_0026)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0026)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_52:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0026 step code.
;------------------------------------------------------------------------------
lbl_53:
                ; -- Start of transition --
                ;  Precondition gpsInput == ':'
step_gps_State_0026: MOVLW    .58
                CPFSEQ   gpsInput, A
                GOTO     lbl_54
                ;  Transition GOTO gps_State_0027
                MOVLW    HIGH(step_gps_State_0027)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0027)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_54:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0027 step code.
;------------------------------------------------------------------------------
lbl_55:
                ; -- Start of transition --
                ;  Precondition gpsInput == '0'
step_gps_State_0027: MOVLW    .48
                CPFSEQ   gpsInput, A
                GOTO     lbl_56
                ;  Command gpsFlags:9 := false
                BCF      (gpsFlags + .1), 1, A
                ;  Transition GOTO (Shared) root
                GOTO     enter_root
                ; -- Start of transition --
                ;  Precondition gpsInput == '1'
lbl_56:         MOVLW    .49
                CPFSEQ   gpsInput, A
                GOTO     lbl_57
                ;  Command gpsFlags:9 := true
                BSF      (gpsFlags + .1), 1, A
                ;  Transition GOTO (Shared) root
                GOTO     enter_root
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_57:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node dollar entry code.
;------------------------------------------------------------------------------
lbl_58:
              ;  Command PORTC:0 := true
enter_dollar: BSF      PORTC, 0, A
              ;  Transition GOTO dollar
              MOVLW    HIGH(step_dollar)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(step_dollar)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; Node dollar step code.
;------------------------------------------------------------------------------
                ; -- Start of transition --
                ;  Precondition gpsInput == 'G'
step_dollar:    MOVLW    .71
                CPFSEQ   gpsInput, A
                GOTO     lbl_59
                ;  Transition GOTO gps_State_0043
                MOVLW    HIGH(step_gps_State_0043)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0043)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_59:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0043 step code.
;------------------------------------------------------------------------------
lbl_60:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'P'
step_gps_State_0043: MOVLW    .80
                CPFSEQ   gpsInput, A
                GOTO     lbl_61
                ;  Transition GOTO gps_State_0044
                MOVLW    HIGH(step_gps_State_0044)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0044)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_61:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0044 step code.
;------------------------------------------------------------------------------
lbl_62:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'G'
step_gps_State_0044: MOVLW    .71
                CPFSEQ   gpsInput, A
                GOTO     lbl_63
                ;  Transition GOTO gps_State_0045
                MOVLW    HIGH(step_gps_State_0045)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0045)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_63:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0045 step code.
;------------------------------------------------------------------------------
lbl_64:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'G'
step_gps_State_0045: MOVLW    .71
                CPFSEQ   gpsInput, A
                GOTO     lbl_65
                ;  Transition GOTO gps_State_0046
                MOVLW    HIGH(step_gps_State_0046)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0046)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_65:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0046 step code.
;------------------------------------------------------------------------------
lbl_66:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'A'
step_gps_State_0046: MOVLW    .65
                CPFSEQ   gpsInput, A
                GOTO     lbl_67
                ;  Precondition Flag gpsFlags:0 == false
                BTFSC    gpsFlags, 0, A
                GOTO     lbl_67
                ;  Transition GOTO gps_State_0047
                MOVLW    HIGH(step_gps_State_0047)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0047)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_67:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0047 step code.
;------------------------------------------------------------------------------
lbl_68:
                ; -- Start of transition --
                ;  Precondition gpsInput == ','
step_gps_State_0047: MOVLW    .44
                CPFSEQ   gpsInput, A
                GOTO     lbl_69
                  ;  Prepare for Gosub. Subroutine will return to lbl_70
                  MOVLW    HIGH(lbl_70)
                  MOVWF    (_subReturn + .1), A
                  MOVLW    LOW(lbl_70)
                  MOVWF    _subReturn, A
                  ;  Command gps_storeCount := 0
                  CLRF     gps_storeCount, A
                  ;  Command gpsTime := 0
                  BANKSEL  gpsTime
                  CLRF     gpsTime
                  CLRF     (gpsTime + .1)
                  CLRF     (gpsTime + .2)
                  CLRF     (gpsTime + .3)
                  CLRF     (gpsTime + .4)
                  CLRF     (gpsTime + .5)
                  ;  Transition GOTO readGpsTime
                  MOVLW    HIGH(step_readGpsTime)
                  MOVWF    (_statePtr + .1), A
                  MOVLW    LOW(step_readGpsTime)
                  MOVWF    _statePtr, A
                  RETURN   
                  ;  Prepare for Gosub. Subroutine will return to lbl_71
lbl_70:           MOVLW    HIGH(lbl_71)
                  MOVWF    (_subReturn + .1), A
                  MOVLW    LOW(lbl_71)
                  MOVWF    _subReturn, A
                  ;  Command gps_storeCount := 0
                  CLRF     gps_storeCount, A
                  ;  Command gpsLatitudeDegMin := 0
                  CLRF     gpsLatitudeDegMin
                  CLRF     (gpsLatitudeDegMin + .1)
                  CLRF     (gpsLatitudeDegMin + .2)
                  CLRF     (gpsLatitudeDegMin + .3)
                  ;  Transition GOTO readLatLong
                  MOVLW    HIGH(step_readLatLong)
                  MOVWF    (_statePtr + .1), A
                  MOVLW    LOW(step_readLatLong)
                  MOVWF    _statePtr, A
                  RETURN   
                ;  Transition GOTO gps_State_0048
lbl_71:         MOVLW    HIGH(step_gps_State_0048)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0048)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_69:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0048 step code.
;------------------------------------------------------------------------------
lbl_72:
                ; -- Start of transition --
                ;  Command gpsQuality := gpsInput
step_gps_State_0048: MOVFF    gpsInput, gpsQuality
                ;  Command gpsFlags:0 := true
                BSF      gpsFlags, 0, A
                ;  Transition GOTO (Shared) root
                GOTO     enter_root

;------------------------------------------------------------------------------
; Node readLatLong step code.
;------------------------------------------------------------------------------
lbl_73:
                ; -- Start of transition --
                ;  Precondition gpsInput >= '0'
step_readLatLong: MOVLW    .47
                CPFSGT   gpsInput, A
                GOTO     lbl_74
                ;  Precondition gpsInput <= '9'
                MOVLW    .58
                CPFSLT   gpsInput, A
                GOTO     lbl_74
                ;  Precondition gps_storeCount <= 0x02
                MOVLW    .3
                CPFSLT   gps_storeCount, A
                GOTO     lbl_74
                ;  Command gpsLatitudeDegMin[gps_storeCount] := gpsInput
                LFSR     FSR0, gpsLatitudeDegMin
                MOVF     gps_storeCount, W, A
                MOVFF    gpsInput, PLUSW0
                ;  Command gps_storeCount++
                INCF     gps_storeCount, F, A
                ;  Transition GOTO SELF
                RETURN   
                ; -- Start of transition --
                ;  Precondition gpsInput >= '0'
lbl_74:         MOVLW    .47
                CPFSGT   gpsInput, A
                GOTO     lbl_75
                ;  Precondition gpsInput <= '9'
                MOVLW    .58
                CPFSLT   gpsInput, A
                GOTO     lbl_75
                ;  Precondition gps_storeCount == 0x03
                MOVLW    .3
                CPFSEQ   gps_storeCount, A
                GOTO     lbl_75
                ;  Command gpsLatitudeDegMin[gps_storeCount] := gpsInput
                LFSR     FSR0, gpsLatitudeDegMin
                MOVF     gps_storeCount, W, A
                MOVFF    gpsInput, PLUSW0
                ;  Command gps_storeCount++
                INCF     gps_storeCount, F, A
                ;  Transition GOTO gps_State_0031
                MOVLW    HIGH(step_gps_State_0031)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0031)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_75:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0031 step code.
;------------------------------------------------------------------------------
lbl_76:
                ; -- Start of transition --
                ;  Precondition gpsInput == '.'
step_gps_State_0031: MOVLW    .46
                CPFSEQ   gpsInput, A
                GOTO     lbl_77
                ;  Command gps_storeCount := 0
                CLRF     gps_storeCount, A
                ;  Command gpsLatitudeHundredths := 0
                BANKSEL  gpsLatitudeHundredths
                CLRF     gpsLatitudeHundredths
                CLRF     (gpsLatitudeHundredths + .1)
                ;  Transition GOTO gps_State_0032
                MOVLW    HIGH(step_gps_State_0032)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0032)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_77:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0032 step code.
;------------------------------------------------------------------------------
lbl_78:
                ; -- Start of transition --
                ;  Precondition gpsInput >= '0'
step_gps_State_0032: MOVLW    .47
                CPFSGT   gpsInput, A
                GOTO     lbl_79
                ;  Precondition gpsInput <= '9'
                MOVLW    .58
                CPFSLT   gpsInput, A
                GOTO     lbl_79
                ;  Precondition gps_storeCount <= 0x00
                MOVLW    .1
                CPFSLT   gps_storeCount, A
                GOTO     lbl_79
                ;  Command gpsLatitudeHundredths[gps_storeCount] := gpsInput
                LFSR     FSR0, gpsLatitudeHundredths
                MOVF     gps_storeCount, W, A
                MOVFF    gpsInput, PLUSW0
                ;  Command gps_storeCount++
                INCF     gps_storeCount, F, A
                ;  Transition GOTO SELF
                RETURN   
                ; -- Start of transition --
                ;  Precondition gpsInput >= '0'
lbl_79:         MOVLW    .47
                CPFSGT   gpsInput, A
                GOTO     lbl_80
                ;  Precondition gpsInput <= '9'
                MOVLW    .58
                CPFSLT   gpsInput, A
                GOTO     lbl_80
                ;  Precondition gps_storeCount == 0x01
                MOVLW    .1
                CPFSEQ   gps_storeCount, A
                GOTO     lbl_80
                ;  Command gpsLatitudeHundredths[gps_storeCount] := gpsInput
                LFSR     FSR0, gpsLatitudeHundredths
                MOVF     gps_storeCount, W, A
                MOVFF    gpsInput, PLUSW0
                ;  Command gps_storeCount++
                INCF     gps_storeCount, F, A
                ;  Transition GOTO gps_State_0033
                MOVLW    HIGH(step_gps_State_0033)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0033)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_80:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0033 step code.
;------------------------------------------------------------------------------
lbl_81:
                ; -- Start of transition --
                ;  Precondition gpsInput == '$'
step_gps_State_0033: MOVLW    .36
                CPFSEQ   gpsInput, A
                GOTO     lbl_82
                ;  Transition GOTO (Shared) dollar
                GOTO     enter_dollar
                ; -- Start of transition --
                ;  Precondition gpsInput == ','
lbl_82:         MOVLW    .44
                CPFSEQ   gpsInput, A
                GOTO     lbl_83
                ;  Transition GOTO gps_State_0034
                MOVLW    HIGH(step_gps_State_0034)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0034)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO SELF
lbl_83:         RETURN   

;------------------------------------------------------------------------------
; Node gps_State_0034 step code.
;------------------------------------------------------------------------------
lbl_84:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'S'
step_gps_State_0034: MOVLW    .83
                CPFSEQ   gpsInput, A
                GOTO     lbl_85
                ;  Command gpsFlags:1 := false
                BCF      gpsFlags, 1, A
                ;  Transition GOTO gps_State_0035
                MOVLW    HIGH(step_gps_State_0035)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0035)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Precondition gpsInput == 'N'
lbl_85:         MOVLW    .78
                CPFSEQ   gpsInput, A
                GOTO     lbl_86
                ;  Command gpsFlags:1 := true
                BSF      gpsFlags, 1, A
                ;  Transition GOTO gps_State_0035
                MOVLW    HIGH(step_gps_State_0035)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0035)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_86:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0035 step code.
;------------------------------------------------------------------------------
lbl_87:
                ; -- Start of transition --
                ;  Precondition gpsInput == ','
step_gps_State_0035: MOVLW    .44
                CPFSEQ   gpsInput, A
                GOTO     lbl_88
                ;  Command gps_storeCount := 0
                CLRF     gps_storeCount, A
                ;  Command gpsLongitudeDegMin := 0
                BANKSEL  gpsLongitudeDegMin
                CLRF     gpsLongitudeDegMin
                CLRF     (gpsLongitudeDegMin + .1)
                CLRF     (gpsLongitudeDegMin + .2)
                CLRF     (gpsLongitudeDegMin + .3)
                CLRF     (gpsLongitudeDegMin + .4)
                ;  Transition GOTO gps_State_0036
                MOVLW    HIGH(step_gps_State_0036)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0036)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_88:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0036 step code.
;------------------------------------------------------------------------------
lbl_89:
                ; -- Start of transition --
                ;  Precondition gpsInput >= '0'
step_gps_State_0036: MOVLW    .47
                CPFSGT   gpsInput, A
                GOTO     lbl_90
                ;  Precondition gpsInput <= '9'
                MOVLW    .58
                CPFSLT   gpsInput, A
                GOTO     lbl_90
                ;  Precondition gps_storeCount <= 0x03
                MOVLW    .4
                CPFSLT   gps_storeCount, A
                GOTO     lbl_90
                ;  Command gpsLongitudeDegMin[gps_storeCount] := gpsInput
                LFSR     FSR0, gpsLongitudeDegMin
                MOVF     gps_storeCount, W, A
                MOVFF    gpsInput, PLUSW0
                ;  Command gps_storeCount++
                INCF     gps_storeCount, F, A
                ;  Transition GOTO SELF
                RETURN   
                ; -- Start of transition --
                ;  Precondition gpsInput >= '0'
lbl_90:         MOVLW    .47
                CPFSGT   gpsInput, A
                GOTO     lbl_91
                ;  Precondition gpsInput <= '9'
                MOVLW    .58
                CPFSLT   gpsInput, A
                GOTO     lbl_91
                ;  Precondition gps_storeCount == 0x04
                MOVLW    .4
                CPFSEQ   gps_storeCount, A
                GOTO     lbl_91
                ;  Command gpsLongitudeDegMin[gps_storeCount] := gpsInput
                LFSR     FSR0, gpsLongitudeDegMin
                MOVF     gps_storeCount, W, A
                MOVFF    gpsInput, PLUSW0
                ;  Command gps_storeCount++
                INCF     gps_storeCount, F, A
                ;  Transition GOTO gps_State_0037
                MOVLW    HIGH(step_gps_State_0037)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0037)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_91:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0037 step code.
;------------------------------------------------------------------------------
lbl_92:
                ; -- Start of transition --
                ;  Precondition gpsInput == '.'
step_gps_State_0037: MOVLW    .46
                CPFSEQ   gpsInput, A
                GOTO     lbl_93
                ;  Command gps_storeCount := 0
                CLRF     gps_storeCount, A
                ;  Command gpsLongitudeHundredths := 0
                BANKSEL  gpsLongitudeHundredths
                CLRF     gpsLongitudeHundredths
                CLRF     (gpsLongitudeHundredths + .1)
                ;  Transition GOTO gps_State_0038
                MOVLW    HIGH(step_gps_State_0038)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0038)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_93:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0038 step code.
;------------------------------------------------------------------------------
lbl_94:
                ; -- Start of transition --
                ;  Precondition gpsInput >= '0'
step_gps_State_0038: MOVLW    .47
                CPFSGT   gpsInput, A
                GOTO     lbl_95
                ;  Precondition gpsInput <= '9'
                MOVLW    .58
                CPFSLT   gpsInput, A
                GOTO     lbl_95
                ;  Precondition gps_storeCount <= 0x00
                MOVLW    .1
                CPFSLT   gps_storeCount, A
                GOTO     lbl_95
                ;  Command gpsLongitudeHundredths[gps_storeCount] := gpsInput
                LFSR     FSR0, gpsLongitudeHundredths
                MOVF     gps_storeCount, W, A
                MOVFF    gpsInput, PLUSW0
                ;  Command gps_storeCount++
                INCF     gps_storeCount, F, A
                ;  Transition GOTO SELF
                RETURN   
                ; -- Start of transition --
                ;  Precondition gpsInput >= '0'
lbl_95:         MOVLW    .47
                CPFSGT   gpsInput, A
                GOTO     lbl_96
                ;  Precondition gpsInput <= '9'
                MOVLW    .58
                CPFSLT   gpsInput, A
                GOTO     lbl_96
                ;  Precondition gps_storeCount == 0x01
                MOVLW    .1
                CPFSEQ   gps_storeCount, A
                GOTO     lbl_96
                ;  Command gpsLongitudeHundredths[gps_storeCount] := gpsInput
                LFSR     FSR0, gpsLongitudeHundredths
                MOVF     gps_storeCount, W, A
                MOVFF    gpsInput, PLUSW0
                ;  Command gps_storeCount++
                INCF     gps_storeCount, F, A
                ;  Transition GOTO gps_State_0039
                MOVLW    HIGH(step_gps_State_0039)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0039)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_96:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0039 step code.
;------------------------------------------------------------------------------
lbl_97:
                ; -- Start of transition --
                ;  Precondition gpsInput == '$'
step_gps_State_0039: MOVLW    .36
                CPFSEQ   gpsInput, A
                GOTO     lbl_98
                ;  Transition GOTO (Shared) dollar
                GOTO     enter_dollar
                ; -- Start of transition --
                ;  Precondition gpsInput == ','
lbl_98:         MOVLW    .44
                CPFSEQ   gpsInput, A
                GOTO     lbl_99
                ;  Transition GOTO gps_State_0040
                MOVLW    HIGH(step_gps_State_0040)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0040)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO SELF
lbl_99:         RETURN   

;------------------------------------------------------------------------------
; Node gps_State_0040 step code.
;------------------------------------------------------------------------------
lbl_100:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'E'
step_gps_State_0040: MOVLW    .69
                CPFSEQ   gpsInput, A
                GOTO     lbl_101
                ;  Command gpsFlags:2 := true
                BSF      gpsFlags, 2, A
                ;  Transition GOTO gps_State_0041
                MOVLW    HIGH(step_gps_State_0041)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0041)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Precondition gpsInput == 'W'
lbl_101:        MOVLW    .87
                CPFSEQ   gpsInput, A
                GOTO     lbl_102
                ;  Command gpsFlags:2 := false
                BCF      gpsFlags, 2, A
                ;  Transition GOTO gps_State_0041
                MOVLW    HIGH(step_gps_State_0041)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0041)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_102:        GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0041 step code.
;------------------------------------------------------------------------------
lbl_103:
                ; -- Start of transition --
                ;  Precondition gpsInput == ','
step_gps_State_0041: MOVLW    .44
                CPFSEQ   gpsInput, A
                GOTO     lbl_104
                ;  Return from subroutine
                CLRF     PCLATU, A
                MOVFF    (_subReturn + .1), PCLATH
                MOVF     _subReturn, W, A
                MOVWF    PCL, A
                ;  Transition GOTO (Shared) root
                GOTO     enter_root
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_104:        GOTO     enter_root

;------------------------------------------------------------------------------
; Node readGpsTime step code.
;------------------------------------------------------------------------------
lbl_105:
                ; -- Start of transition --
                ;  Precondition gpsInput >= '0'
step_readGpsTime: MOVLW    .47
                CPFSGT   gpsInput, A
                GOTO     lbl_106
                ;  Precondition gpsInput <= '9'
                MOVLW    .58
                CPFSLT   gpsInput, A
                GOTO     lbl_106
                ;  Precondition gps_storeCount <= 0x04
                MOVLW    .5
                CPFSLT   gps_storeCount, A
                GOTO     lbl_106
                ;  Command gpsTime[gps_storeCount] := gpsInput
                LFSR     FSR0, gpsTime
                MOVF     gps_storeCount, W, A
                MOVFF    gpsInput, PLUSW0
                ;  Command gps_storeCount++
                INCF     gps_storeCount, F, A
                ;  Transition GOTO SELF
                RETURN   
                ; -- Start of transition --
                ;  Precondition gpsInput >= '0'
lbl_106:        MOVLW    .47
                CPFSGT   gpsInput, A
                GOTO     lbl_107
                ;  Precondition gpsInput <= '9'
                MOVLW    .58
                CPFSLT   gpsInput, A
                GOTO     lbl_107
                ;  Precondition gps_storeCount == 0x05
                MOVLW    .5
                CPFSEQ   gps_storeCount, A
                GOTO     lbl_107
                ;  Command gpsTime[gps_storeCount] := gpsInput
                LFSR     FSR0, gpsTime
                MOVF     gps_storeCount, W, A
                MOVFF    gpsInput, PLUSW0
                ;  Command gps_storeCount++
                INCF     gps_storeCount, F, A
                ;  Transition GOTO gps_State_0029
                MOVLW    HIGH(step_gps_State_0029)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0029)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_107:        GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0029 step code.
;------------------------------------------------------------------------------
lbl_108:
                ; -- Start of transition --
                ;  Precondition gpsInput == '$'
step_gps_State_0029: MOVLW    .36
                CPFSEQ   gpsInput, A
                GOTO     lbl_109
                ;  Transition GOTO (Shared) dollar
                GOTO     enter_dollar
                ; -- Start of transition --
                ;  Precondition gpsInput == ','
lbl_109:        MOVLW    .44
                CPFSEQ   gpsInput, A
                GOTO     lbl_110
                ;  Return from subroutine
                CLRF     PCLATU, A
                MOVFF    (_subReturn + .1), PCLATH
                MOVF     _subReturn, W, A
                MOVWF    PCL, A
                ;  Transition GOTO (Shared) root
                GOTO     enter_root
                ; -- Start of transition --
                ;  Transition GOTO SELF
lbl_110:        RETURN   

              END
