;------------------------------------------------------------------------------
; This file was auto-generated by PICStateGenerator. Do not edit.
; Generated: Tue Nov 15 20:56:26 GMT 2011
;------------------------------------------------------------------------------
              list     p=18F14K50
#include "p18f14k50.inc"

              GLOBAL   gpsInit
              GLOBAL   gpsStep
              GLOBAL   gpsLatitudeDegMin
              GLOBAL   gpsFlags
              GLOBAL   gpsLongitudeHundredths
              GLOBAL   gpsTime
              GLOBAL   testSendVar
              GLOBAL   gpsLongitudeDegMin
              GLOBAL   gpsQuality
              GLOBAL   testSendIndex
              GLOBAL   gpsLatitudeHundredths
              GLOBAL   gpsInput

gpsAcs        UDATA_ACS
_statePtr              res .2
_subReturn             res .2
gpsFlags               res .2
gps_storeCount         res .1
gpsInput               res .1

              ; Please set up the linker to locate this block as required.
gpsBank1      UDATA
gpsLatitudeDegMin      res .4
gpsLongitudeHundredths   res .2
gpsTime                res .6
testSendVar            res .1
gpsLongitudeDegMin     res .5
gpsQuality             res .1
testSendIndex          res .1
gpsLatitudeHundredths   res .2

gpsCode       CODE

;------------------------------------------------------------------------------
; State model initialisation.
;------------------------------------------------------------------------------
gpsInit:      MOVLW    HIGH(step_root)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(step_root)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; State model entry point.
; This method executes the code for the current state.
;------------------------------------------------------------------------------
gpsStep:      CLRF     PCLATU, A
              MOVFF    (_statePtr + .1), PCLATH
              MOVF     _statePtr, W, A
              MOVWF    PCL, A

;------------------------------------------------------------------------------
; Node root entry code.
;------------------------------------------------------------------------------
              ;  Command PORTC:0 := false
enter_root:   BCF      PORTC, 0, A
              ;  Transition GOTO root
              MOVLW    HIGH(step_root)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(step_root)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; Node root step code.
;------------------------------------------------------------------------------
                ; -- Start of transition --
                ;  Precondition gpsInput == '$'
step_root:      MOVLW    .36
                CPFSEQ   gpsInput, A
                GOTO     lbl_0
                ;  Transition GOTO (Shared) dollar
                GOTO     enter_dollar
                ; -- Start of transition --
                ;  Precondition gpsInput == '!'
lbl_0:          MOVLW    .33
                CPFSEQ   gpsInput, A
                GOTO     lbl_1
                ;  Transition GOTO (Shared) gps_State_0000
                GOTO     enter_gps_State_0000
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_1:          GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0000 entry code.
;------------------------------------------------------------------------------
lbl_2:
              ;  Transition GOTO gps_State_0000
enter_gps_State_0000: MOVLW    HIGH(step_gps_State_0000)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(step_gps_State_0000)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; Node gps_State_0000 step code.
;------------------------------------------------------------------------------
                ; -- Start of transition --
                ;  Precondition gpsInput == '!'
step_gps_State_0000: MOVLW    .33
                CPFSEQ   gpsInput, A
                GOTO     lbl_3
                ;  Precondition Flag gpsFlags:3 == false
                BTFSC    gpsFlags, 3, A
                GOTO     lbl_3
                ;  Command PORTC:1 := true
                BSF      PORTC, 1, A
                ;  Transition GOTO gps_State_0001
                MOVLW    HIGH(step_gps_State_0001)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0001)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_3:          GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0001 step code.
;------------------------------------------------------------------------------
lbl_4:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'T'
step_gps_State_0001: MOVLW    .84
                CPFSEQ   gpsInput, A
                GOTO     lbl_5
                ;  Transition GOTO gps_State_0002
                MOVLW    HIGH(step_gps_State_0002)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0002)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_5:          GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0002 step code.
;------------------------------------------------------------------------------
lbl_6:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'E'
step_gps_State_0002: MOVLW    .69
                CPFSEQ   gpsInput, A
                GOTO     lbl_7
                ;  Transition GOTO gps_State_0003
                MOVLW    HIGH(step_gps_State_0003)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0003)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_7:          GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0003 step code.
;------------------------------------------------------------------------------
lbl_8:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'S'
step_gps_State_0003: MOVLW    .83
                CPFSEQ   gpsInput, A
                GOTO     lbl_9
                ;  Transition GOTO gps_State_0004
                MOVLW    HIGH(step_gps_State_0004)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0004)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_9:          GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0004 step code.
;------------------------------------------------------------------------------
lbl_10:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'T'
step_gps_State_0004: MOVLW    .84
                CPFSEQ   gpsInput, A
                GOTO     lbl_11
                ;  Transition GOTO gps_State_0005
                MOVLW    HIGH(step_gps_State_0005)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0005)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_11:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0005 step code.
;------------------------------------------------------------------------------
lbl_12:
                ; -- Start of transition --
                ;  Precondition gpsInput == '-'
step_gps_State_0005: MOVLW    .45
                CPFSEQ   gpsInput, A
                GOTO     lbl_13
                ;  Transition GOTO gps_State_0006
                MOVLW    HIGH(step_gps_State_0006)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0006)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_13:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0006 step code.
;------------------------------------------------------------------------------
lbl_14:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'S'
step_gps_State_0006: MOVLW    .83
                CPFSEQ   gpsInput, A
                GOTO     lbl_15
                ;  Transition GOTO gps_State_0007
                MOVLW    HIGH(step_gps_State_0007)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0007)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_15:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0007 step code.
;------------------------------------------------------------------------------
lbl_16:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'E'
step_gps_State_0007: MOVLW    .69
                CPFSEQ   gpsInput, A
                GOTO     lbl_17
                ;  Transition GOTO gps_State_0008
                MOVLW    HIGH(step_gps_State_0008)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0008)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_17:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0008 step code.
;------------------------------------------------------------------------------
lbl_18:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'N'
step_gps_State_0008: MOVLW    .78
                CPFSEQ   gpsInput, A
                GOTO     lbl_19
                ;  Transition GOTO gps_State_0009
                MOVLW    HIGH(step_gps_State_0009)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0009)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_19:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0009 step code.
;------------------------------------------------------------------------------
lbl_20:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'D'
step_gps_State_0009: MOVLW    .68
                CPFSEQ   gpsInput, A
                GOTO     lbl_21
                ;  Transition GOTO gps_State_0010
                MOVLW    HIGH(step_gps_State_0010)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0010)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_21:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0010 step code.
;------------------------------------------------------------------------------
lbl_22:
                ; -- Start of transition --
                ;  Precondition gpsInput == ':'
step_gps_State_0010: MOVLW    .58
                CPFSEQ   gpsInput, A
                GOTO     lbl_23
                ;  Command gps_storeCount := 0
                CLRF     gps_storeCount, A
                ;  Command testSendVar := 0
                BANKSEL  testSendVar
                CLRF     testSendVar
                ;  Transition GOTO gps_State_0011
                MOVLW    HIGH(step_gps_State_0011)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0011)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_23:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0011 step code.
;------------------------------------------------------------------------------
lbl_24:
                ; -- Start of transition --
                ;  Precondition gpsInput >= '0'
step_gps_State_0011: MOVLW    .47
                CPFSGT   gpsInput, A
                GOTO     lbl_25
                ;  Precondition gpsInput <= '9'
                MOVLW    .58
                CPFSLT   gpsInput, A
                GOTO     lbl_25
                ;  Command testSendVar[gps_storeCount] := gpsInput
                LFSR     FSR0, testSendVar
                MOVF     gps_storeCount, W, A
                MOVFF    gpsInput, PLUSW0
                ;  Command gps_storeCount++
                INCF     gps_storeCount, F, A
                ;  Transition GOTO gps_State_0012
                MOVLW    HIGH(step_gps_State_0012)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0012)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_25:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0012 step code.
;------------------------------------------------------------------------------
lbl_26:
                ; -- Start of transition --
                ;  Precondition gpsInput == ':'
step_gps_State_0012: MOVLW    .58
                CPFSEQ   gpsInput, A
                GOTO     lbl_27
                ;  Command gps_storeCount := 0
                CLRF     gps_storeCount, A
                ;  Command testSendIndex := 0
                BANKSEL  testSendIndex
                CLRF     testSendIndex
                ;  Transition GOTO gps_State_0013
                MOVLW    HIGH(step_gps_State_0013)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0013)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_27:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0013 step code.
;------------------------------------------------------------------------------
lbl_28:
                ; -- Start of transition --
                ;  Precondition gpsInput >= '0'
step_gps_State_0013: MOVLW    .47
                CPFSGT   gpsInput, A
                GOTO     lbl_29
                ;  Precondition gpsInput <= '9'
                MOVLW    .58
                CPFSLT   gpsInput, A
                GOTO     lbl_29
                ;  Command testSendIndex[gps_storeCount] := gpsInput
                LFSR     FSR0, testSendIndex
                MOVF     gps_storeCount, W, A
                MOVFF    gpsInput, PLUSW0
                ;  Command gps_storeCount++
                INCF     gps_storeCount, F, A
                ;  Command gpsFlags:3 := true
                BSF      gpsFlags, 3, A
                ;  Command PORTC:1 := false
                BCF      PORTC, 1, A
                ;  Transition GOTO (Shared) root
                GOTO     enter_root
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_29:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node dollar entry code.
;------------------------------------------------------------------------------
lbl_30:
              ;  Command PORTC:0 := true
enter_dollar: BSF      PORTC, 0, A
              ;  Transition GOTO dollar
              MOVLW    HIGH(step_dollar)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(step_dollar)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; Node dollar step code.
;------------------------------------------------------------------------------
                ; -- Start of transition --
                ;  Precondition gpsInput == 'G'
step_dollar:    MOVLW    .71
                CPFSEQ   gpsInput, A
                GOTO     lbl_31
                ;  Transition GOTO gps_State_0029
                MOVLW    HIGH(step_gps_State_0029)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0029)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_31:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0029 step code.
;------------------------------------------------------------------------------
lbl_32:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'P'
step_gps_State_0029: MOVLW    .80
                CPFSEQ   gpsInput, A
                GOTO     lbl_33
                ;  Transition GOTO gps_State_0030
                MOVLW    HIGH(step_gps_State_0030)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0030)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_33:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0030 step code.
;------------------------------------------------------------------------------
lbl_34:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'G'
step_gps_State_0030: MOVLW    .71
                CPFSEQ   gpsInput, A
                GOTO     lbl_35
                ;  Transition GOTO gps_State_0031
                MOVLW    HIGH(step_gps_State_0031)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0031)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_35:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0031 step code.
;------------------------------------------------------------------------------
lbl_36:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'G'
step_gps_State_0031: MOVLW    .71
                CPFSEQ   gpsInput, A
                GOTO     lbl_37
                ;  Transition GOTO gps_State_0032
                MOVLW    HIGH(step_gps_State_0032)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0032)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_37:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0032 step code.
;------------------------------------------------------------------------------
lbl_38:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'A'
step_gps_State_0032: MOVLW    .65
                CPFSEQ   gpsInput, A
                GOTO     lbl_39
                ;  Precondition Flag gpsFlags:0 == false
                BTFSC    gpsFlags, 0, A
                GOTO     lbl_39
                ;  Transition GOTO gps_State_0033
                MOVLW    HIGH(step_gps_State_0033)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0033)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_39:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0033 step code.
;------------------------------------------------------------------------------
lbl_40:
                ; -- Start of transition --
                ;  Precondition gpsInput == ','
step_gps_State_0033: MOVLW    .44
                CPFSEQ   gpsInput, A
                GOTO     lbl_41
                  ;  Prepare for Gosub. Subroutine will return to lbl_42
                  MOVLW    HIGH(lbl_42)
                  MOVWF    (_subReturn + .1), A
                  MOVLW    LOW(lbl_42)
                  MOVWF    _subReturn, A
                  ;  Command gps_storeCount := 0
                  CLRF     gps_storeCount, A
                  ;  Command gpsTime := 0
                  BANKSEL  gpsTime
                  CLRF     gpsTime
                  CLRF     (gpsTime + .1)
                  CLRF     (gpsTime + .2)
                  CLRF     (gpsTime + .3)
                  CLRF     (gpsTime + .4)
                  CLRF     (gpsTime + .5)
                  ;  Transition GOTO readGpsTime
                  MOVLW    HIGH(step_readGpsTime)
                  MOVWF    (_statePtr + .1), A
                  MOVLW    LOW(step_readGpsTime)
                  MOVWF    _statePtr, A
                  RETURN   
                  ;  Prepare for Gosub. Subroutine will return to lbl_43
lbl_42:           MOVLW    HIGH(lbl_43)
                  MOVWF    (_subReturn + .1), A
                  MOVLW    LOW(lbl_43)
                  MOVWF    _subReturn, A
                  ;  Command gps_storeCount := 0
                  CLRF     gps_storeCount, A
                  ;  Command gpsLatitudeDegMin := 0
                  CLRF     gpsLatitudeDegMin
                  CLRF     (gpsLatitudeDegMin + .1)
                  CLRF     (gpsLatitudeDegMin + .2)
                  CLRF     (gpsLatitudeDegMin + .3)
                  ;  Transition GOTO readLatLong
                  MOVLW    HIGH(step_readLatLong)
                  MOVWF    (_statePtr + .1), A
                  MOVLW    LOW(step_readLatLong)
                  MOVWF    _statePtr, A
                  RETURN   
                ;  Transition GOTO gps_State_0034
lbl_43:         MOVLW    HIGH(step_gps_State_0034)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0034)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_41:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0034 step code.
;------------------------------------------------------------------------------
lbl_44:
                ; -- Start of transition --
                ;  Command gpsQuality := gpsInput
step_gps_State_0034: MOVFF    gpsInput, gpsQuality
                ;  Command gpsFlags:0 := true
                BSF      gpsFlags, 0, A
                ;  Transition GOTO (Shared) root
                GOTO     enter_root

;------------------------------------------------------------------------------
; Node readLatLong step code.
;------------------------------------------------------------------------------
lbl_45:
                ; -- Start of transition --
                ;  Precondition gpsInput >= '0'
step_readLatLong: MOVLW    .47
                CPFSGT   gpsInput, A
                GOTO     lbl_46
                ;  Precondition gpsInput <= '9'
                MOVLW    .58
                CPFSLT   gpsInput, A
                GOTO     lbl_46
                ;  Precondition gps_storeCount <= 0x02
                MOVLW    .3
                CPFSLT   gps_storeCount, A
                GOTO     lbl_46
                ;  Command gpsLatitudeDegMin[gps_storeCount] := gpsInput
                LFSR     FSR0, gpsLatitudeDegMin
                MOVF     gps_storeCount, W, A
                MOVFF    gpsInput, PLUSW0
                ;  Command gps_storeCount++
                INCF     gps_storeCount, F, A
                ;  Transition GOTO SELF
                RETURN   
                ; -- Start of transition --
                ;  Precondition gpsInput >= '0'
lbl_46:         MOVLW    .47
                CPFSGT   gpsInput, A
                GOTO     lbl_47
                ;  Precondition gpsInput <= '9'
                MOVLW    .58
                CPFSLT   gpsInput, A
                GOTO     lbl_47
                ;  Precondition gps_storeCount == 0x03
                MOVLW    .3
                CPFSEQ   gps_storeCount, A
                GOTO     lbl_47
                ;  Command gpsLatitudeDegMin[gps_storeCount] := gpsInput
                LFSR     FSR0, gpsLatitudeDegMin
                MOVF     gps_storeCount, W, A
                MOVFF    gpsInput, PLUSW0
                ;  Command gps_storeCount++
                INCF     gps_storeCount, F, A
                ;  Transition GOTO gps_State_0017
                MOVLW    HIGH(step_gps_State_0017)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0017)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_47:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0017 step code.
;------------------------------------------------------------------------------
lbl_48:
                ; -- Start of transition --
                ;  Precondition gpsInput == '.'
step_gps_State_0017: MOVLW    .46
                CPFSEQ   gpsInput, A
                GOTO     lbl_49
                ;  Command gps_storeCount := 0
                CLRF     gps_storeCount, A
                ;  Command gpsLatitudeHundredths := 0
                BANKSEL  gpsLatitudeHundredths
                CLRF     gpsLatitudeHundredths
                CLRF     (gpsLatitudeHundredths + .1)
                ;  Transition GOTO gps_State_0018
                MOVLW    HIGH(step_gps_State_0018)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0018)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_49:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0018 step code.
;------------------------------------------------------------------------------
lbl_50:
                ; -- Start of transition --
                ;  Precondition gpsInput >= '0'
step_gps_State_0018: MOVLW    .47
                CPFSGT   gpsInput, A
                GOTO     lbl_51
                ;  Precondition gpsInput <= '9'
                MOVLW    .58
                CPFSLT   gpsInput, A
                GOTO     lbl_51
                ;  Precondition gps_storeCount <= 0x00
                MOVLW    .1
                CPFSLT   gps_storeCount, A
                GOTO     lbl_51
                ;  Command gpsLatitudeHundredths[gps_storeCount] := gpsInput
                LFSR     FSR0, gpsLatitudeHundredths
                MOVF     gps_storeCount, W, A
                MOVFF    gpsInput, PLUSW0
                ;  Command gps_storeCount++
                INCF     gps_storeCount, F, A
                ;  Transition GOTO SELF
                RETURN   
                ; -- Start of transition --
                ;  Precondition gpsInput >= '0'
lbl_51:         MOVLW    .47
                CPFSGT   gpsInput, A
                GOTO     lbl_52
                ;  Precondition gpsInput <= '9'
                MOVLW    .58
                CPFSLT   gpsInput, A
                GOTO     lbl_52
                ;  Precondition gps_storeCount == 0x01
                MOVLW    .1
                CPFSEQ   gps_storeCount, A
                GOTO     lbl_52
                ;  Command gpsLatitudeHundredths[gps_storeCount] := gpsInput
                LFSR     FSR0, gpsLatitudeHundredths
                MOVF     gps_storeCount, W, A
                MOVFF    gpsInput, PLUSW0
                ;  Command gps_storeCount++
                INCF     gps_storeCount, F, A
                ;  Transition GOTO gps_State_0019
                MOVLW    HIGH(step_gps_State_0019)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0019)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_52:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0019 step code.
;------------------------------------------------------------------------------
lbl_53:
                ; -- Start of transition --
                ;  Precondition gpsInput == '$'
step_gps_State_0019: MOVLW    .36
                CPFSEQ   gpsInput, A
                GOTO     lbl_54
                ;  Transition GOTO (Shared) dollar
                GOTO     enter_dollar
                ; -- Start of transition --
                ;  Precondition gpsInput == ','
lbl_54:         MOVLW    .44
                CPFSEQ   gpsInput, A
                GOTO     lbl_55
                ;  Transition GOTO gps_State_0020
                MOVLW    HIGH(step_gps_State_0020)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0020)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO SELF
lbl_55:         RETURN   

;------------------------------------------------------------------------------
; Node gps_State_0020 step code.
;------------------------------------------------------------------------------
lbl_56:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'S'
step_gps_State_0020: MOVLW    .83
                CPFSEQ   gpsInput, A
                GOTO     lbl_57
                ;  Command gpsFlags:1 := false
                BCF      gpsFlags, 1, A
                ;  Transition GOTO gps_State_0021
                MOVLW    HIGH(step_gps_State_0021)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0021)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Precondition gpsInput == 'N'
lbl_57:         MOVLW    .78
                CPFSEQ   gpsInput, A
                GOTO     lbl_58
                ;  Command gpsFlags:1 := true
                BSF      gpsFlags, 1, A
                ;  Transition GOTO gps_State_0021
                MOVLW    HIGH(step_gps_State_0021)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0021)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_58:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0021 step code.
;------------------------------------------------------------------------------
lbl_59:
                ; -- Start of transition --
                ;  Precondition gpsInput == ','
step_gps_State_0021: MOVLW    .44
                CPFSEQ   gpsInput, A
                GOTO     lbl_60
                ;  Command gps_storeCount := 0
                CLRF     gps_storeCount, A
                ;  Command gpsLongitudeDegMin := 0
                BANKSEL  gpsLongitudeDegMin
                CLRF     gpsLongitudeDegMin
                CLRF     (gpsLongitudeDegMin + .1)
                CLRF     (gpsLongitudeDegMin + .2)
                CLRF     (gpsLongitudeDegMin + .3)
                CLRF     (gpsLongitudeDegMin + .4)
                ;  Transition GOTO gps_State_0022
                MOVLW    HIGH(step_gps_State_0022)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0022)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_60:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0022 step code.
;------------------------------------------------------------------------------
lbl_61:
                ; -- Start of transition --
                ;  Precondition gpsInput >= '0'
step_gps_State_0022: MOVLW    .47
                CPFSGT   gpsInput, A
                GOTO     lbl_62
                ;  Precondition gpsInput <= '9'
                MOVLW    .58
                CPFSLT   gpsInput, A
                GOTO     lbl_62
                ;  Precondition gps_storeCount <= 0x03
                MOVLW    .4
                CPFSLT   gps_storeCount, A
                GOTO     lbl_62
                ;  Command gpsLongitudeDegMin[gps_storeCount] := gpsInput
                LFSR     FSR0, gpsLongitudeDegMin
                MOVF     gps_storeCount, W, A
                MOVFF    gpsInput, PLUSW0
                ;  Command gps_storeCount++
                INCF     gps_storeCount, F, A
                ;  Transition GOTO SELF
                RETURN   
                ; -- Start of transition --
                ;  Precondition gpsInput >= '0'
lbl_62:         MOVLW    .47
                CPFSGT   gpsInput, A
                GOTO     lbl_63
                ;  Precondition gpsInput <= '9'
                MOVLW    .58
                CPFSLT   gpsInput, A
                GOTO     lbl_63
                ;  Precondition gps_storeCount == 0x04
                MOVLW    .4
                CPFSEQ   gps_storeCount, A
                GOTO     lbl_63
                ;  Command gpsLongitudeDegMin[gps_storeCount] := gpsInput
                LFSR     FSR0, gpsLongitudeDegMin
                MOVF     gps_storeCount, W, A
                MOVFF    gpsInput, PLUSW0
                ;  Command gps_storeCount++
                INCF     gps_storeCount, F, A
                ;  Transition GOTO gps_State_0023
                MOVLW    HIGH(step_gps_State_0023)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0023)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_63:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0023 step code.
;------------------------------------------------------------------------------
lbl_64:
                ; -- Start of transition --
                ;  Precondition gpsInput == '.'
step_gps_State_0023: MOVLW    .46
                CPFSEQ   gpsInput, A
                GOTO     lbl_65
                ;  Command gps_storeCount := 0
                CLRF     gps_storeCount, A
                ;  Command gpsLongitudeHundredths := 0
                BANKSEL  gpsLongitudeHundredths
                CLRF     gpsLongitudeHundredths
                CLRF     (gpsLongitudeHundredths + .1)
                ;  Transition GOTO gps_State_0024
                MOVLW    HIGH(step_gps_State_0024)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0024)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_65:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0024 step code.
;------------------------------------------------------------------------------
lbl_66:
                ; -- Start of transition --
                ;  Precondition gpsInput >= '0'
step_gps_State_0024: MOVLW    .47
                CPFSGT   gpsInput, A
                GOTO     lbl_67
                ;  Precondition gpsInput <= '9'
                MOVLW    .58
                CPFSLT   gpsInput, A
                GOTO     lbl_67
                ;  Precondition gps_storeCount <= 0x00
                MOVLW    .1
                CPFSLT   gps_storeCount, A
                GOTO     lbl_67
                ;  Command gpsLongitudeHundredths[gps_storeCount] := gpsInput
                LFSR     FSR0, gpsLongitudeHundredths
                MOVF     gps_storeCount, W, A
                MOVFF    gpsInput, PLUSW0
                ;  Command gps_storeCount++
                INCF     gps_storeCount, F, A
                ;  Transition GOTO SELF
                RETURN   
                ; -- Start of transition --
                ;  Precondition gpsInput >= '0'
lbl_67:         MOVLW    .47
                CPFSGT   gpsInput, A
                GOTO     lbl_68
                ;  Precondition gpsInput <= '9'
                MOVLW    .58
                CPFSLT   gpsInput, A
                GOTO     lbl_68
                ;  Precondition gps_storeCount == 0x01
                MOVLW    .1
                CPFSEQ   gps_storeCount, A
                GOTO     lbl_68
                ;  Command gpsLongitudeHundredths[gps_storeCount] := gpsInput
                LFSR     FSR0, gpsLongitudeHundredths
                MOVF     gps_storeCount, W, A
                MOVFF    gpsInput, PLUSW0
                ;  Command gps_storeCount++
                INCF     gps_storeCount, F, A
                ;  Transition GOTO gps_State_0025
                MOVLW    HIGH(step_gps_State_0025)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0025)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_68:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0025 step code.
;------------------------------------------------------------------------------
lbl_69:
                ; -- Start of transition --
                ;  Precondition gpsInput == '$'
step_gps_State_0025: MOVLW    .36
                CPFSEQ   gpsInput, A
                GOTO     lbl_70
                ;  Transition GOTO (Shared) dollar
                GOTO     enter_dollar
                ; -- Start of transition --
                ;  Precondition gpsInput == ','
lbl_70:         MOVLW    .44
                CPFSEQ   gpsInput, A
                GOTO     lbl_71
                ;  Transition GOTO gps_State_0026
                MOVLW    HIGH(step_gps_State_0026)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0026)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO SELF
lbl_71:         RETURN   

;------------------------------------------------------------------------------
; Node gps_State_0026 step code.
;------------------------------------------------------------------------------
lbl_72:
                ; -- Start of transition --
                ;  Precondition gpsInput == 'E'
step_gps_State_0026: MOVLW    .69
                CPFSEQ   gpsInput, A
                GOTO     lbl_73
                ;  Command gpsFlags:2 := true
                BSF      gpsFlags, 2, A
                ;  Transition GOTO gps_State_0027
                MOVLW    HIGH(step_gps_State_0027)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0027)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Precondition gpsInput == 'W'
lbl_73:         MOVLW    .87
                CPFSEQ   gpsInput, A
                GOTO     lbl_74
                ;  Command gpsFlags:2 := false
                BCF      gpsFlags, 2, A
                ;  Transition GOTO gps_State_0027
                MOVLW    HIGH(step_gps_State_0027)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0027)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_74:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0027 step code.
;------------------------------------------------------------------------------
lbl_75:
                ; -- Start of transition --
                ;  Precondition gpsInput == ','
step_gps_State_0027: MOVLW    .44
                CPFSEQ   gpsInput, A
                GOTO     lbl_76
                ;  Return from subroutine
                CLRF     PCLATU, A
                MOVFF    (_subReturn + .1), PCLATH
                MOVF     _subReturn, W, A
                MOVWF    PCL, A
                ;  Transition GOTO (Shared) root
                GOTO     enter_root
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_76:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node readGpsTime step code.
;------------------------------------------------------------------------------
lbl_77:
                ; -- Start of transition --
                ;  Precondition gpsInput >= '0'
step_readGpsTime: MOVLW    .47
                CPFSGT   gpsInput, A
                GOTO     lbl_78
                ;  Precondition gpsInput <= '9'
                MOVLW    .58
                CPFSLT   gpsInput, A
                GOTO     lbl_78
                ;  Precondition gps_storeCount <= 0x04
                MOVLW    .5
                CPFSLT   gps_storeCount, A
                GOTO     lbl_78
                ;  Command gpsTime[gps_storeCount] := gpsInput
                LFSR     FSR0, gpsTime
                MOVF     gps_storeCount, W, A
                MOVFF    gpsInput, PLUSW0
                ;  Command gps_storeCount++
                INCF     gps_storeCount, F, A
                ;  Transition GOTO SELF
                RETURN   
                ; -- Start of transition --
                ;  Precondition gpsInput >= '0'
lbl_78:         MOVLW    .47
                CPFSGT   gpsInput, A
                GOTO     lbl_79
                ;  Precondition gpsInput <= '9'
                MOVLW    .58
                CPFSLT   gpsInput, A
                GOTO     lbl_79
                ;  Precondition gps_storeCount == 0x05
                MOVLW    .5
                CPFSEQ   gps_storeCount, A
                GOTO     lbl_79
                ;  Command gpsTime[gps_storeCount] := gpsInput
                LFSR     FSR0, gpsTime
                MOVF     gps_storeCount, W, A
                MOVFF    gpsInput, PLUSW0
                ;  Command gps_storeCount++
                INCF     gps_storeCount, F, A
                ;  Transition GOTO gps_State_0015
                MOVLW    HIGH(step_gps_State_0015)
                MOVWF    (_statePtr + .1), A
                MOVLW    LOW(step_gps_State_0015)
                MOVWF    _statePtr, A
                RETURN   
                ; -- Start of transition --
                ;  Transition GOTO (Shared) root
lbl_79:         GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0015 step code.
;------------------------------------------------------------------------------
lbl_80:
                ; -- Start of transition --
                ;  Precondition gpsInput == '$'
step_gps_State_0015: MOVLW    .36
                CPFSEQ   gpsInput, A
                GOTO     lbl_81
                ;  Transition GOTO (Shared) dollar
                GOTO     enter_dollar
                ; -- Start of transition --
                ;  Precondition gpsInput == ','
lbl_81:         MOVLW    .44
                CPFSEQ   gpsInput, A
                GOTO     lbl_82
                ;  Return from subroutine
                CLRF     PCLATU, A
                MOVFF    (_subReturn + .1), PCLATH
                MOVF     _subReturn, W, A
                MOVWF    PCL, A
                ;  Transition GOTO (Shared) root
                GOTO     enter_root
                ; -- Start of transition --
                ;  Transition GOTO SELF
lbl_82:         RETURN   

              END
